import '@/assets/styles/fonts.css';
import '@/assets/styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body>{children}</body>
  </html>
);

export default RootLayout;
