fragment SectionTrendFragment on SectionTrend {
  sectionTitle
  shoes {
    data {
      attributes {
        name
        options {
          ...ShoeOptionFragment
        }
        type {
          data {
            attributes {
              ...TypeFragment
            }
          }
        }
        price
      }
    }
  }
}
