// import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';

// import { strapiApi } from '@/src/utils/api';
import styles from '@/styles/Home.module.css';

// const inter = Inter({ subsets: ['latin'] });

// export async function getStaticProps(_context: any) {
//   const response = await strapiApi.request.get('/tests/1');
//   console.log('response', _context, response.data);
//   return {
//     props: { data: response.data.data } // will be passed to the page component as props
//   };
// }

const Home = () => (
  <>
    <h1 className='font-nike'>EVERYTHING TO THE MAX</h1>
    <h1 className='font-sans'>Whereas recognition of the inherent dignity</h1>
    {/* <h1 className='text-3xl font-bold underline'>{data.attributes.test}</h1> */}
    <Head>
      <title>Create Next App</title>
      <meta content='Generated by create next app' name='description' />
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <link href='/favicon.ico' rel='icon' />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            rel='noopener noreferrer'
            target='_blank'
          >
            By{' '}
            <Image
              priority
              alt='Vercel Logo'
              className={styles.vercelLogo}
              height={24}
              src='/vercel.svg'
              width={100}
            />
          </a>
        </div>
      </div>

      <div className={styles.center}>
        <Image
          priority
          alt='Next.js Logo'
          className={styles.logo}
          height={37}
          src='/next.svg'
          width={180}
        />
        <div className={styles.thirteen}>
          <Image priority alt='13' height={31} src='/thirteen.svg' width={40} />
        </div>
      </div>

      <div className={styles.grid}>
        <a
          className={styles.card}
          href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          rel='noopener noreferrer'
          target='_blank'
        >
          <h2>
            Docs <span>-&gt;</span>
          </h2>
          <p>Find in-depth information about Next.js features and&nbsp;API.</p>
        </a>

        <a
          className={styles.card}
          href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          rel='noopener noreferrer'
          target='_blank'
        >
          <h2>
            Learn <span>-&gt;</span>
          </h2>
          <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
        </a>

        <a
          className={styles.card}
          href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          rel='noopener noreferrer'
          target='_blank'
        >
          <h2>
            Templates <span>-&gt;</span>
          </h2>
          <p>Discover and deploy boilerplate example Next.js&nbsp;projects.</p>
        </a>

        <a
          className={styles.card}
          href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          rel='noopener noreferrer'
          target='_blank'
        >
          <h2>
            Deploy <span>-&gt;</span>
          </h2>
          <p>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
        </a>
      </div>
    </main>
  </>
);

export default Home;
